:sectnums:
:sectnumlevels: 5
:toc: left
:toclevels: 3
:page-layout: docs
:source-highlighter: highlightjs
:icons: font

= Notes for pentesting

== IP

=== netdiscover

 sudo netdiscover -i vboxnet0 -r 192.168.99.0/24

Hint: -r /24 is broken with 0.3-beta7 and libcap 1.10

Result:

 Currently scanning: 172.26.183.0/16   |   Screen View: Unique Hosts
 2 Captured ARP Req/Rep packets, from 2 hosts.   Total size: 102
 ______________________________________________________________________
   IP            At MAC Address     Count     Len  MAC Vendor / Hostname
 ----------------------------------------------------------------------
 192.168.99.11   08:00:27:9a:83:e3      1      42  PCS Systemtechnik GmbH
 192.168.99.104  08:00:27:11:10:25      1      60  PCS Systemtechnik GmbH


=== nmap

https://security.stackexchange.com/questions/36198/how-to-find-live-hosts-on-my-network

 nmap -sn  -PS22,3389  192.168.99.0/2

 Starting Nmap 7.92 ( https://nmap.org ) at 2022-01-04 11:03 CET
 Nmap scan report for 192.168.99.1
 Host is up (0.00051s latency).
 Nmap scan report for 192.168.99.11
 Host is up (0.00029s latency).
 Nmap scan report for 192.168.99.104
 Host is up (0.00026s latency).
 Nmap done: 256 IP addresses (3 hosts up) scanned in 11.99 seconds

=== arp

 arp -a -n

Note: fastest!!, but works only after an nmap scan??

 ...
 ? (192.168.99.104) at 8:0:27:11:10:25 on vboxnet0 ifscope [ethernet]
 ...

== Ports

=== nmap

 nmap 192.168.99.105 -sV -A -vv --version-intensity 5 -sC --packet-trace

Example Output:

 80/tcp open  http    syn-ack Apache httpd 2.4.48 ((Debian))
 | http-methods:
 |_  Supported Methods: GET POST OPTIONS HEAD
 | http-robots.txt: 1 disallowed entry
 |_/~myfiles
 |_http-title: Site doesn't have a title (text/html).
 Service Info: OS: Linux; CPE: cpe:/o:linux:linux_kernel

== HTTP enumeration

=== enumeration via brute force
Query the http server for all its content via a wordlist.

==== dirb

----
dirb http://box:80 ~/dev/src/tools/dirb-kali-master/wordlists/common.txt
----
Example

 ---- Entering directory: http://box:80/image/ ----
 (!) WARNING: Directory IS LISTABLE. No need to scan it.
 (Use mode '-w' if you want to scan it anyway)
 ---- Entering directory: http://box:80/javascript/ ----
 ==> DIRECTORY: http://box:80/javascript/jquery/

==== gobuster

----
gobuster dir -r -u http://box:80 --wordlist ~/dev/src/tools/dirb-kali-master/wordlists/common.txt -x txt,php,html --no-error
----

Example output
----
===============================================================
Gobuster v3.1.0
by OJ Reeves (@TheColonial) & Christian Mehlmauer (@firefart)
===============================================================
[+] Url:                     http://box:80
[+] Method:                  GET
[+] Threads:                 10
[+] Wordlist:                /Users/dirkkutzer/dev/src/tools/dirb-kali-master/wordlists/common.txt
[+] Negative Status codes:   404
[+] User Agent:              gobuster/3.1.0
[+] Extensions:              html,txt,php
[+] Follow Redirect:         true
[+] Timeout:                 10s
===============================================================
2022/01/06 20:17:09 Starting gobuster in directory enumeration mode
===============================================================
/.hta                 (Status: 403) [Size: 268]
/.htaccess.html       (Status: 403) [Size: 268]
/.hta.txt             (Status: 403) [Size: 268]
/.htpasswd            (Status: 403) [Size: 268]
/.htaccess            (Status: 403) [Size: 268]
/.hta.php             (Status: 403) [Size: 268]
/.hta.html            (Status: 403) [Size: 268]
/.htpasswd.txt        (Status: 403) [Size: 268]
/.htaccess.txt        (Status: 403) [Size: 268]
/.htpasswd.php        (Status: 403) [Size: 268]
/.htaccess.php        (Status: 403) [Size: 268]
/.htpasswd.html       (Status: 403) [Size: 268]
/image                (Status: 200) [Size: 942]
/index.html           (Status: 200) [Size: 333]
/index.html           (Status: 200) [Size: 333]
/javascript           (Status: 403) [Size: 268]
/manual               (Status: 200) [Size: 676]
/robots.txt           (Status: 200) [Size: 34]
/robots.txt           (Status: 200) [Size: 34]
/server-status        (Status: 403) [Size: 268]

===============================================================
2022/01/06 20:17:11 Finished
===============================================================
----
=== download specific content

==== curl
----
curl -vv -L http://box:80/~myfiles
----
|=======================
|param|meaning      |example
|-vv    |verbose output     |
|-k    |ignore tls/ssl     |
|-L    |follow redirects     |
|=======================

=== enumerate via substitution

==== ffuf

===== simple substitution
----
ffuf -c -ic -r -u 'http://box/~FUZZ' -w ~/dev/src/tools/dirb-kali-master/wordlists/big.txt -e .php,.txt,.html -fc 403
----

Example Output

 :: Method           : GET
 :: URL              : http://box/~FUZZ
 :: Wordlist         : FUZZ: wordlists/big.txt
 :: Extensions       : .php .txt .html
 :: Follow redirects : true
 :: Calibration      : false
 :: Timeout          : 10
 :: Threads          : 40
 :: Matcher          : Response status: 200,204,301,302,307,401,403,405
 :: Filter           : Response status: 403
 ________________________________________________
 myfiles                 [Status: 200, Size: 147, Words: 11, Lines: 15]
 secret                  [Status: 200, Size: 331, Words: 52, Lines: 6]

====== find hidden files

----
ffuf -c -ic -r -u 'http://box/~secret/.FUZZ' -w ~/dev/src/tools/rockyou.txt -e .php,.txt,.html -fc 403
----

 :: Method           : GET
 :: URL              : http://box/~secret/.FUZZ
 :: Wordlist         : FUZZ: /Users/dirkkutzer/dev/src/tools/rockyou.txt
 :: Extensions       : .php .txt .html
 :: Follow redirects : true
 :: Calibration      : false
 :: Timeout          : 10
 :: Threads          : 40
 :: Matcher          : Response status: 200,204,301,302,307,401,403,405
 :: Filter           : Response status: 403
 ________________________________________________
                         [Status: 200, Size: 331, Words: 52, Lines: 6]
 mysecret.txt            [Status: 200, Size: 4689, Words: 1, Lines: 2]

== scanner

=== nmap
https://securitytrails.com/blog/nmap-vulnerability-scan
----
nmap --script vuln -sV box
----

Example Output

 Starting Nmap 7.92 ( https://nmap.org ) at 2022-01-06 20:49 CET
 Pre-scan script results:
 | broadcast-avahi-dos:
 |   Discovered hosts:
 |     224.0.0.251
 |   After NULL UDP avahi packet DoS (CVE-2011-1002).
 |_  Hosts are all up (not vulnerable).
 Nmap scan report for box (192.168.99.105)
 Host is up (0.10s latency).
 Not shown: 998 closed tcp ports (conn-refused)
 PORT   STATE SERVICE VERSION
 22/tcp open  ssh     OpenSSH 8.4p1 Debian 5 (protocol 2.0)
 | vulners:
 |   cpe:/a:openbsd:openssh:8.4p1:
 |     	MSF:ILITIES/GENTOO-LINUX-CVE-2021-28041/	4.6	https://vulners.com/metasploit/MSF:ILITIES/GENTOO-LINUX-CVE-2021-28041/	*EXPLOIT*
 |     	CVE-2021-28041	4.6	https://vulners.com/cve/CVE-2021-28041
 |     	CVE-2021-41617	4.4	https://vulners.com/cve/CVE-2021-41617
 |     	MSF:ILITIES/OPENBSD-OPENSSH-CVE-2020-14145/	4.3	https://vulners.com/metasploit/MSF:ILITIES/OPENBSD-OPENSSH-CVE-2020-14145/	*EXPLOIT*
 |     	MSF:ILITIES/HUAWEI-EULEROS-2_0_SP9-CVE-2020-14145/	4.3	https://vulners.com/metasploit/MSF:ILITIES/HUAWEI-EULEROS-2_0_SP9-CVE-2020-14145/	*EXPLOIT*
 |     	MSF:ILITIES/HUAWEI-EULEROS-2_0_SP8-CVE-2020-14145/	4.3	https://vulners.com/metasploit/MSF:ILITIES/HUAWEI-EULEROS-2_0_SP8-CVE-2020-14145/	*EXPLOIT*
 |     	MSF:ILITIES/HUAWEI-EULEROS-2_0_SP5-CVE-2020-14145/	4.3	https://vulners.com/metasploit/MSF:ILITIES/HUAWEI-EULEROS-2_0_SP5-CVE-2020-14145/	*EXPLOIT*
 |     	MSF:ILITIES/F5-BIG-IP-CVE-2020-14145/	4.3	https://vulners.com/metasploit/MSF:ILITIES/F5-BIG-IP-CVE-2020-14145/	*EXPLOIT*
 |     	CVE-2020-14145	4.3	https://vulners.com/cve/CVE-2020-14145
 |_    	CVE-2016-20012	4.3	https://vulners.com/cve/CVE-2016-20012
 80/tcp open  http    Apache httpd 2.4.48 ((Debian))
 |_http-dombased-xss: Couldn't find any DOM based XSS.
 |_http-csrf: Couldn't find any CSRF vulnerabilities.
 | vulners:
 |   cpe:/a:apache:http_server:2.4.48:
 |     	CVE-2021-44790	7.5	https://vulners.com/cve/CVE-2021-44790
 |     	CVE-2021-39275	7.5	https://vulners.com/cve/CVE-2021-39275
 |     	FDF3DFA1-ED74-5EE2-BF5C-BA752CA34AE8	6.8	https://vulners.com/githubexploit/FDF3DFA1-ED74-5EE2-BF5C-BA752CA34AE8	*EXPLOIT*
 |     	CVE-2021-40438	6.8	https://vulners.com/cve/CVE-2021-40438
 |     	4810E2D9-AC5F-5B08-BFB3-DDAFA2F63332	6.8	https://vulners.com/githubexploit/4810E2D9-AC5F-5B08-BFB3-DDAFA2F63332	*EXPLOIT*
 |     	CVE-2021-44224	6.4	https://vulners.com/cve/CVE-2021-44224
 |     	CVE-2021-36160	5.0	https://vulners.com/cve/CVE-2021-36160
 |     	CVE-2021-34798	5.0	https://vulners.com/cve/CVE-2021-34798
 |      CVE-2021-33193	5.0	https://vulners.com/cve/CVE-2021-33193
 |_     MSF:EXPLOIT/UNIX/WEBAPP/JOOMLA_MEDIA_UPLOAD_EXEC/	0.0	https://vulners.com/metasploit/MSF:EXPLOIT/UNIX/WEBAPP/JOOMLA_MEDIA_UPLOAD_EXEC/	*EXPLOIT*
 | http-enum:
 |   /robots.txt: Robots file
 |   /image/: Potentially interesting directory w/ listing on 'apache/2.4.48 (debian)'
 |_  /manual/: Potentially interesting folder
 |_http-server-header: Apache/2.4.48 (Debian)
 |_http-stored-xss: Couldn't find any stored XSS vulnerabilities.
 Service Info: OS: Linux; CPE: cpe:/o:linux:linux_kernel
